config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index'

  resources :user_sessions, only: [:new, :create, :destroy]
  resources :products, only: [:edit, :update, :destroy]

  get  'login'  => 'user_sessions#new',     :as => :login
  post 'logout' => 'user_sessions#destroy', :as => :logout
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
class Product < ApplicationRecord
  acts_as_paranoid

  def price_with_sale
    price * (1 - sale)
  end

end

app/models/user.rb
class User < ApplicationRecord
  authenticates_with_sorcery!
  enum role: {
    employee: 0,
    management: 10,
    admin: 20
  }

  def user_name(id)
    @user = User.find(id)
    @user.first_name + ' ' + @user.last_name
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :require_login

  private

  def not_authenticated
    redirect_to login_path, alert: 'Please login first'
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_before_action :require_login

  def index
    @products = Product.with_deleted.all.order(:title)
    # render text: 'Welcome home, %username%!', layout: true
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :find_product

  def update
    if @product.update(product_params)
      redirect_to root_url, notice: 'product was successfully updated'
    else
      render :edit
    end
  end

  def destroy
    if current_user
      if current_user.role == 'admin'
        if @product.destroy
            flash[:notice] = 'product was successfully deleted'
          else
            flash[:error] = 'an error occurred'
        end
      end
    end
    redirect_to root_url
  end

  private

  def find_product
    @product = Product.find(params[:id])
  end

  def product_params
    params.require(:product).permit(:title, :articul, :price, :sale)
  end
end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
  skip_before_action :require_login, except: [:destroy]

  def new
    @user = User.new
  end

  def create
    if @user = login(params[:email], params[:password])
      redirect_back_or_to(root_path, notice: 'Login successful')
    else
      flash.now[:alert] = 'Login failed'
      render action: 'new'
    end
  end

  def destroy
    logout
    redirect_to(root_path, notice: 'Logged out!')
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def product_title(product)
    # split,map,join are for the case when title is downcase
    "#{product.title.split(' ').map(&:capitalize).join(' ')} ##{product.articul.upcase}"
  end

  def product_price(product)
    price = product.sale.zero? ? product.price : 2 * product.price
    number_to_currency(price)
  end

end

app/helpers/user_sessions_helper.rb
module UserSessionsHelper
end

app/views/home/_product.html.erb
<div class="product">
  <% unless (!product.deleted_at.nil?) && (current_user.nil?) %>
    <div class="title">
    <span<%== ' class="archived"' unless product.deleted_at.nil? %>>
      <%= product_title(product) %>
    </span>
    </div>
    <div class="price">
    <span<%== ' class="old-price"' unless product.sale.zero? %>>
      <%= product_price(product) %>
    </span>
      <% unless product.sale.zero? %>
      <span>
        <%= number_to_currency(product.price_with_sale) %>
      </span>
      <% end %>
    </div>
  <% end %>
    <div class="actions">
      <% if current_user %>
          <%= link_to 'Edit', edit_product_path(product) if (%w(admin management employee).include?(current_user.role))&&(product.deleted_at.nil?) %>
          <%= link_to 'Archive', product, method: :delete if (%w(admin management).include?(current_user.role))&&(product.deleted_at.nil?) %>
          <% if (current_user.role == 'admin') && product.updated_by %>
              <%= 'Updated by:' %><%= link_to 'User name', root_url %>
          <% end %>
      <% end %>
    </div>
</div>

app/views/home/index.html.erb
<div>
  <% if current_user %>
    <%= link_to 'Default view', root_url if current_user.role == 'admin' %>
  <% end %>
</div>
<%= render partial: 'product', collection: @products %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CandidateTask</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div id="nav">
      <% if current_user %>
        <%= link_to 'Logout', :logout, method: :post %>
      <% else %>
        <%= link_to 'Login', :login %>
      <% end %>
    </div>
    <div>
      <p id="notice"><%= flash[:notice] %></p>
      <p id="alert"><%= flash[:alert] %></p>
    </div>
    <%= yield %>
  </body>
</html>

app/views/products/edit.html.erb
<%= form_for @product do |f| %>
  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :articul %><br />
    <%= f.text_field :articul %>
  </div>
  <div class="field">
    <%= f.label :price %><br />
    <%= f.text_field :price %>
  </div>
  <div class="field">
    <%= f.label :sale %><br />
    <%= f.text_field :sale %>
  </div>
  <div class="actions">
    <%= f.submit 'Save' %>
  </div>
<% end %>

app/views/user_sessions/_form.html.erb
<%= form_tag user_sessions_path, :method => :post do %>
  <div class="field">
    <%= label_tag :email %><br />
    <%= text_field_tag :email %>
  </div>
  <div class="field">
    <%= label_tag :password %><br />
    <%= password_field_tag :password %>
  </div>
  <div class="actions">
    <%= submit_tag 'Login' %>
  </div>
<% end %>

app/views/user_sessions/new.html.erb
<h1>Login</h1>

<%= render 'form' %>

<%= link_to 'Back', root_path %>